apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.service.name }}
  labels:
    {{- include "Shop_product.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort:  {{ .Values.service.targetport }}
      protocol:  {{ .Values.service.protocol }}
      name: http
  selector:
    {{- include "Shop_product.selectorLabels" . | nindent 4 }}
